name: WallWar
main: com.mengcraft.wallwar.Main
version: 1.0
author: mengcraft

commands:
  wall:
    description: None.
    permission: wall.admin

permissions:
  wall.admin:
    description: None.
    default: op

depend:
- WorldEdit