name: WallWar
main: com.mengcraft.wallwar.Main
version: ${project.version}
author: mengcraft

commands:
  wall:
    description: None.
    permission: wall.admin

permissions:
  wall.admin:
    description: None.
    default: op

depend:
- WorldEdit
- MapRestore
- iTag
- SimpleORM
